### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by joaoestudante** [joaoestudante/radiologo#11]
A detailed permission model is required to allow fine-grained access control to resources and actions.

This _may_ imply the usage of either another library or moving from class-based views to method-based views, since DRF does not cleanly support authorization for specific methods in a class, only globally for the class.

In a perfect world, we would have something like this:

```python
class ListCreateProgramsView(APIView):

    @scope('list_all_programs')
    def get(self, request):
        programs = [program for program in Program.objects.all()]
        serialized = ProgramSerializer(programs, many=True)
        return Response(serialized.data, status=status.HTTP_200_OK)
```
And this way, only someone who is granted access to `list_all_programs` could complete the request successfully.

If we end up using API Keys like suggested in #10, this "scope" would have to validate if the API key contains the specified scope, and if the user making the request (in case there is the bearer token in the request's headers) does, too.

**Comment by ricardojorgerm** [comment]
In the documentation, when creating custom permissions:

> If you need to test if a request is a read operation or a write operation, you should check the request method against the constant SAFE_METHODS, which is a tuple containing 'GET', 'OPTIONS' and 'HEAD'. For example:
> 
```
if request.method in permissions.SAFE_METHODS:
    # Check permissions for read-only request
else:
    # Check permissions for write request
```

This allows you to distinguish different operations inside a view, and gives you the granularity you wished.
